### ISSUE TITLE
Property 'setBackNavigation' does not exist on type 'ShellUIService'

### ISSUE THREAD

**Issue by lemaiwo** [SAP/ui5-typescript#342] opened 2022-02-21 08:37 UTC
Hi,

Not sure this is related to the types or the UI5 api but I'm getting following error when using 'setBackNavigation':
![image](https://user-images.githubusercontent.com/5943183/154914047-ee9f61f8-f9a3-4a6d-ae64-093ebfbe3219.png)

This does works perfectly but this function is not described in the types nor the UI5 api.

Kr, Wouter

**Comment by akudev** [comment] 2022-02-21 18:04
Hi,

basically, as long as the type definitions and the official documentation at https://ui5.sap.com/ is in sync, there's probably not a bug in the TypeScript generation. 
If the original developer did not make a method public in the code and it's hence also not shown in the regular API documentation, then there is nothing the type definition generator can do about that. Maybe it is by error or by intention, but is something that originates from the UI5 code.
I'd love to track all such issues from here, but response time would be very poor, so it would be better to report any concerns about API visibilities as a normal UI5 bug. 

Regards
Andreas

**Comment by akudev** [comment] 2022-04-04 16:26
I now reported this internally as 2270056652.
@lemaiwo: remember to directly report issues directly for the original component as long as the TypeScript definitions are saying the same as the UI5 documentation. Thanks!

**Comment by MatanTaranto** [comment] 2022-04-07 12:28
Hi,

This appears to be the expected behaviour, as setBackNavigation is indeed a private method, intended for internal SAP use only.

BR,
Matan

**Comment by akudev** [comment] 2022-04-10 19:04
@lemaiwo: according to further feedback from the code owner, the method should remain private for now, as it is not clear what you are trying to achieve and "in most cases there is not real justification to use that method".

Hence I'm closing this ticket now, but I'm not familiar with this API at all, so if you disagree, please explain why you need this method and I can follow up.
(I'd then e.g. open a ticket elsewhere, as this is not TypeScript related, but a general UI5 API topic.)

Regards
Andreas

**Closed by akudev** 2022-04-10 19:04 UTC
Labels: ts-types-esm
