### ISSUE TITLE
Productive use vs. undefined support status.

### ISSUE THREAD

**Issue by AHaury** [SAP/ui5-typescript#432] opened 2024-03-26 16:51 UTC
Hello UI5-TypeScript Project,

First of all many thanks for all your good work! - The possibility to work with TypeScript instead of plain Javascript when developing SAPUI5 applications is a complete game changer. And in the development team I am working in, we would very much like to switch to UI5-TypeScript for our upcoming cloud development project.

There is, however, one thing thing that is still holding us back, namely the undefined support status of the UI5-TypeScript:  On the one hand side, you explicitly encourage productive use. But on the other hand side, you insist on the fact that in case of problems there will be no reliable support in terms of an application component to which issues can be directed via internal Service Now tickets.

To my understanding this is a contradictory and unusual situation: If SAP encourages application development to use ui5-typescript for better productivity and code quality, why don't we go the whole way ensuring internal support in case of problems like this is the standard at SAP, e.g. for sapui5.

Could you please try to clarify this situation beyond the rather short explanation that one can find at https://sap.github.io/ui5-typescript/#where-to-report-issues. 

Many thanks and best regards,
Axel.

**Comment by akudev** [comment] 2024-03-28 10:15
Hi Axel,
ummm... actually, I think this linked section was forgotten to be updated when we declared the type definitions ready for productive use starting with version 1.116.0 (mid July 2023).

There is indeed no specific internal support component for the type definitions, but that's simply because the available ones should be enough: 
- When the issue comes from wrong JSDoc comments for an API in UI5, then open the ticket on the component for the respective control/module where you would report functional issues.
- When the issue is caused by the type generator that translates the JSDoc comments to *.d.ts files, then it would be best to report it here in this repository. Other SAP software also accepts tickets only via GitHub. If for some reason you definitely need an internal ticket, then use the CA-UI5-COR and mention this comment.

The types are indeed meant for productive use now and can be treated like code that is part of UI5. The only difference is the relaxed compatibility rules due to the different nature of type definitions compared to runtime code.

Thanks for pointing me to that section, I will rephrase it.

**Comment by AHaury** [comment] 2024-03-28 10:55
Hi Andreas,
Thank you so much for this clarification!
Best regards,
Axel.

**Comment by akudev** [comment] 2024-03-28 11:03
Fixed on the web page, thanks.

**Closed** 2024-03-28 11:03 UTC
